[bastion]
111.88.247.142

[webservers]
10.0.1.29
10.0.2.19
[webservers:vars]
ansible_user=user
ansible_ssh_private_key_file=~/.ssh/id_ed25519
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o ProxyCommand="ssh -W %h:%p -q user@111.88.247.142 -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no"'
#ansible_ssh_common_args='-o ProxyCommand="ssh -p 22 -W %h:%p -q user@111.88.247.142"'
